version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - ./src:/www:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']